version: '3.8'

# This docker-compose file sets up a development environment. It can be used as a base for production use.

x-worker-common: &worker-template
  build:
    context: ./worker
    # Uncomment the specific line to choose between including playwright or not
    dockerfile: Dockerfile
    target: worker-playwright
    
  environment:
    - ATS_URL=http://api:8000
    - ATS_TOKEN=
    - TZ=Europe/Copenhagen
    - ATS_CAPABILITIES=playwright
  networks:
    - app-network
  depends_on:
    - api

services:
  db:
    image: postgres:latest
    environment:
      # Set a default user / password for the api. Change this for production use.
      POSTGRES_USER: ats_user 
      POSTGRES_PASSWORD: ats_password
      POSTGRES_DB: ats
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data  # Mount named volume to /var/lib/postgresql/data
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Copenhagen
      # Remember to set username and password for production use
      - DATABASE_URL=postgresql://ats_user:ats_password@db:5432/ats
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80"
    networks:
      - app-network
    environment:
      - VITE_ATS_API_BASE_URL=/api  # Set environment variable
      - TZ=Europe/Copenhagen

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
    networks:
      - app-network

  worker01:
    <<: *worker-template
    hostname: worker-01

  worker02:
    <<: *worker-template
    hostname: worker-02

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=galkaev
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
