version: '3.8'

x-worker-common: &worker-template
  image: ats-worker:development
  environment:
    - ATS_URL=http://api:8000/
    - ATS_TOKEN=
    - TZ=Europe/Copenhagen
  networks:
    - app-network
  depends_on:
    - api

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000"
    environment:
      - TZ=Europe/Copenhagen
    networks:
      - app-network
    volumes:
      - api-data:/data  # Mount named volume to /data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80"
    networks:
      - app-network
    environment:
      - VITE_ATS_API_BASE_URL=/api  # Set environment variable
      - TZ=Europe/Copenhagen

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
    networks:
      - app-network

  worker01:
    <<: *worker-template
    hostname: worker-01

  worker02:
    <<: *worker-template
    hostname: worker-02


networks:
  app-network:
    driver: bridge

volumes:
  api-data:
